### ISSUE TITLE
Customization of the initial structure view for Java

### ISSUE THREAD

**Issue by AvvALlV** [SuduIDE/ij-struct-view-layout#1]
Includes support for all original features. Add filters:
- [x] Visibility sort
- [ ] Inherited elements
- [ ] Group methods by definition type

**Comment by yeswolf** [comment]
@AvvALlV I'd describe what's left or close otherwise. For now it looks good enough, so we can leave it as is I think.

**Comment by AvvALlV** [comment]
inheritance and grouping are not generalizable
