### ISSUE TITLE
Add pure text matching for simple properties

### ISSUE THREAD

**Issue by yeswolf** [SuduIDE/ij-struct-view-layout#11]
In the block like this

```
 "properties" : {
        "name": "IDENTIFIER",
        "type": "TYPE"
      },
```

we should be able to match not only by token type, but also by the string representation of such token (```.toSring()``` value to make it simple). 

Why: let's say we have a some-lang-config with 50% of fields we want to display and 50% that we won't. In the language such as JSON they all have "PROPERTY" token type. If we are able to match them by text, we can filter out not needed. Approach - something like 

```
"properties": [
   {
       "id": "name",
       "token": "IDENTIFIER",
       "regexp":  <string representation of RegExp>
   }
]
```

**Comment by yeswolf** [comment]
@AvvALlV Sometimes when we have no time to update the documentation, it always makes sense to leave a short comment about "how it was done in fact". Who knows, may be it's not the same as in the description.

**Comment by AvvALlV** [comment]
Made as in the description
