### ISSUE TITLE
YAML filtering issue for properties not on the top-level

### ISSUE THREAD

**Issue by yeswolf** [SuduIDE/ij-struct-view-layout#18]
## Steps to reproduce

1. Create YAML config as follows:

```
  "yaml": {
    "element": {
      "ext_url": {
        "displayLevel": 1,
        "baseToken": "Key value pair",
        "attributes": {
          "set": ["tag", "text"],
          "unique": [
            "front_key"
          ]
        },
        "baseIcon": "default",
        "text": [
          "front_key"
        ],
        "description": [
          "tag",
          " ",
          "text"
        ]
      }
    },
    "attribute": {
      "property": [
        {
          "id": "front_key",
          "token": "scalar key",
          "regexp": ".*"
        },
        {
          "id": "text",
          "token": "text"
        },
        {
          "id": "tag",
          "token": "tag"
        }
      ]
    }
  }

```

2. Try to filter the file [hass.txt](https://github.com/SuduIDE/ij-struct-view-layout/files/12240233/hass.txt)

3. All key-values are displayed correctly - that's ok. 
4. Change regexp to something else that tries to match keys not on the top-level

## Expected

Keys on any level are matched

## Actual 

Only keys on top-level are matched. 

I've tested it all with the hotfix for matching, that touches only regexp field. So, that's strange.

**Comment by AvvALlV** [comment]
Fixed it
